# Generated by Django 4.2.6 on 2023-10-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Stores',
        ),
    ]
