# Generated by Django 4.2.6 on 2023-10-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='name',
            new_name='mid',
        ),
    ]
