# Generated by Django 4.2.6 on 2023-10-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_name_inquiry_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
